[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rudolph"
version = "0.1.0"
description = "Advent of Code Solutions!"
authors = [{ name = "Juliette H. Lavoie" }]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "advent-of-code-data",
    "networkx",
    "pandas",
    "numpy",
    "click",
    "cloup",
    "pyyaml",
    "loguru",
    "pre-commit",
    "python-dotenv",
    "intervaltree",
    "numba",
    "shapely",
    "scipy",
    "cvxpy[glpk]",
    "ortools",
    "z3-solver"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "isort",
    "types-networkx",
    "scipy-stubs",
    "types-shapely",
]

[tool.ruff]
line-length = 88
target-version = "py313"
extend-select = ["I"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.13"
strict = true
ignore_missing_imports = true
untyped_calls_exclude = ["cvxpy"]

[[tool.mypy.overrides]]
module = "app"
disallow_untyped_decorators = false

[tool.pyright]
reportMissingTypeStubs = false

[dependency-groups]
dev = [
    "scipy-stubs>=1.18.1.1",
    "types-networkx>=3.6.1.20260911",
    "types-shapely>=2.1.0.20260728",
]
